# Generated by Django 2.0.7 on 2018-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0002_auto_20180720_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='register',
            name='emailid',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE'), ('o', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='teesize',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=100),
        ),
    ]
