# Generated by Django 2.0.7 on 2018-08-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0003_auto_20180802_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='prevruns',
            field=models.CharField(choices=[('beg', 'Beginner (0 - 5 runs)'), ('inter', 'Intermediate ( 6 - 10 runs)'), ('pro', 'Professional (10+ runs)')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
