# Generated by Django 2.0.7 on 2018-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0004_auto_20180804_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='prevruns',
            new_name='expr',
        ),
        migrations.AlterField(
            model_name='register',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
